"""Supabase persistence helpers for the API tier.

All Supabase access for the model service is funneled through this module. The
FastAPI app calls these functions; it never talks to Supabase directly. The
Streamlit UI NEVER imports this module -- it does its one read-only query with
the anon key on its own side.

Runs carry a ``run_type`` (``pretrain`` or ``finetune``): pretrain runs record a
held-out LM ``val_loss``; finetune runs record the fine-tuned ``accuracy`` /
``macro_f1`` alongside the from-scratch ``scratch_accuracy`` baseline. We store an
input sequence's **sha256 hash and length** in ``sequence_metadata``, never the
raw characters. Fitted models live in ``run_artifacts`` (not anon-readable).

Environment variables (set locally in a .env, and in the Render dashboard):
    SUPABASE_URL              -> https://<project-ref>.supabase.co
    SUPABASE_SERVICE_KEY      -> the service-role key (server-side only, secret!)
"""
from __future__ import annotations

import os
from typing import List, Optional

from supabase import Client, create_client

_client: Optional[Client] = None

_RUN_COLS = (
    "id,dataset_id,run_type,lr,batch_size,epochs,accuracy,macro_f1,"
    "scratch_accuracy,val_loss,pretrain_run_id,created_at"
)


def get_client() -> Client:
    """Lazily create and cache a Supabase client."""
    global _client
    if _client is None:
        url = os.environ["SUPABASE_URL"]
        key = os.environ["SUPABASE_SERVICE_KEY"]
        _client = create_client(url, key)
    return _client


def ping() -> bool:
    try:
        get_client().table("datasets").select("id").limit(1).execute()
        return True
    except Exception:
        return False


# ---------------------------------------------------------------------------
# datasets  (only the generation parameters -- strings regenerated by seed)
# ---------------------------------------------------------------------------
def insert_dataset(
    name: str, n_rows: int, seq_len: int, vocab_size: int, n_classes: int, seed: int
) -> dict:
    resp = (
        get_client()
        .table("datasets")
        .insert(
            {
                "name": name,
                "n_rows": n_rows,
                "seq_len": seq_len,
                "vocab_size": vocab_size,
                "n_classes": n_classes,
                "seed": seed,
            }
        )
        .execute()
    )
    return resp.data[0]


def get_dataset(dataset_id: int) -> Optional[dict]:
    resp = (
        get_client()
        .table("datasets")
        .select("*")
        .eq("id", dataset_id)
        .limit(1)
        .execute()
    )
    return resp.data[0] if resp.data else None


# ---------------------------------------------------------------------------
# runs  +  run_artifacts
# ---------------------------------------------------------------------------
def _insert_run(row: dict, model_b64: str) -> dict:
    client = get_client()
    run = client.table("runs").insert(row).execute().data[0]
    client.table("run_artifacts").insert(
        {"run_id": run["id"], "model_b64": model_b64}
    ).execute()
    return run


def insert_pretrain_run(
    dataset_id: int,
    lr: float,
    batch_size: int,
    epochs: int,
    val_loss: float,
    model_b64: str,
) -> dict:
    return _insert_run(
        {
            "dataset_id": dataset_id,
            "run_type": "pretrain",
            "lr": lr,
            "batch_size": batch_size,
            "epochs": epochs,
            "val_loss": val_loss,
        },
        model_b64,
    )


def insert_finetune_run(
    dataset_id: int,
    pretrain_run_id: Optional[int],
    lr: float,
    batch_size: int,
    epochs: int,
    pretrained: Optional[dict],
    scratch: dict,
    model_b64: str,
) -> dict:
    return _insert_run(
        {
            "dataset_id": dataset_id,
            "run_type": "finetune",
            "lr": lr,
            "batch_size": batch_size,
            "epochs": epochs,
            "accuracy": pretrained["accuracy"] if pretrained else None,
            "macro_f1": pretrained["macro_f1"] if pretrained else None,
            "scratch_accuracy": scratch["accuracy"],
            "pretrain_run_id": pretrain_run_id,
        },
        model_b64,
    )


def get_run(run_id: int) -> Optional[dict]:
    resp = (
        get_client().table("runs").select(_RUN_COLS).eq("id", run_id).limit(1).execute()
    )
    return resp.data[0] if resp.data else None


def get_run_artifact(run_id: int) -> Optional[str]:
    resp = (
        get_client()
        .table("run_artifacts")
        .select("model_b64")
        .eq("run_id", run_id)
        .limit(1)
        .execute()
    )
    return resp.data[0]["model_b64"] if resp.data else None


def latest_runs(limit: int = 50) -> List[dict]:
    resp = (
        get_client()
        .table("runs")
        .select(_RUN_COLS)
        .order("created_at", desc=True)
        .limit(limit)
        .execute()
    )
    return resp.data


# ---------------------------------------------------------------------------
# sequence_metadata  (hash + length + prediction; NO raw characters)
# ---------------------------------------------------------------------------
def insert_sequence_metadata(
    run_id: int,
    sha256: str,
    length: int,
    label: int,
    class_name: str,
    confidence: float,
) -> dict:
    resp = (
        get_client()
        .table("sequence_metadata")
        .insert(
            {
                "run_id": run_id,
                "sha256": sha256,
                "length": length,
                "label": label,
                "class_name": class_name,
                "confidence": confidence,
            }
        )
        .execute()
    )
    return resp.data[0]
